spring:
  application:
    name: BMI

  datasource:
    url: jdbc:postgresql://localhost:5432/BMI
    username: postgres
    password: 1223
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

openai:
  api-key: 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
  base-url: https://openrouter.ai/api/v1